# permissions for end users to edit prunereports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prunereport-editor-role
rules:
- apiGroups:
  - metering.openshift.io
  resources:
  - prunereports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metering.openshift.io
  resources:
  - prunereports/status
  verbs:
  - get
