# permissions for end users to view recoverreports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: recoverreport-viewer-role
rules:
- apiGroups:
  - metering.openshift.io
  resources:
  - recoverreports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metering.openshift.io
  resources:
  - recoverreports/status
  verbs:
  - get
