## Append samples you want in your CSV to this file as resources ##
resources:
- metering_v1alpha1_recoverreport.yaml
- metering_v1alpha1_prunereport.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
